/* eslint-disable */
// Group Winners
// A       B       C       D
// NED_SEN ENG_USA ARG_POL FRA_AUS
const teams67 = [NED_SEN, IRN_ENG, POL_ARG, FRA_AUS, ESP_GER, MAR_BEL, BRA_SRB, POR_KOR] // 8C7 & 8C6
const teams68 = [NED_SEN, IRN_ENG, POL_ARG, FRA_AUS, ESP_GER, CAN_BEL, BRA_SRB, POR_KOR] // 8C7 & 8C6
const teams71 = [NED_SEN, IRN_ENG, POL_ARG, FRA_AUS, ESP_JPN, MAR_BEL, BRA_SRB, POR_KOR] // 8C7 & 8C6
const teams72 = [NED_SEN, IRN_ENG, POL_ARG, FRA_AUS, ESP_JPN, CAN_BEL, BRA_SRB, POR_KOR] // 8C7 & 8C6
const teams75 = [NED_SEN, IRN_ENG, POL_ARG, FRA_AUS, ESP_GER, MAR_BEL, BRA_CMR, POR_KOR] // 8C7 & 8C6
const teams76 = [NED_SEN, IRN_ENG, POL_ARG, FRA_AUS, ESP_GER, CAN_BEL, BRA_CMR, POR_KOR] // 8C7 & 8C6
const teams79 = [NED_SEN, IRN_ENG, POL_ARG, FRA_AUS, ESP_JPN, MAR_BEL, BRA_CMR, POR_KOR] // 8C7 & 8C6
const teams80 = [NED_SEN, IRN_ENG, POL_ARG, FRA_AUS, ESP_JPN, CAN_BEL, BRA_CMR, POR_KOR] // 8C7 & 8C6
const teams83 = [NED_SEN, IRN_ENG, POL_ARG, FRA_AUS, ESP_GER, MAR_CRO, BRA_SRB, POR_KOR] // 8C7 & 8C6
const teams84 = [NED_SEN, IRN_ENG, POL_ARG, FRA_AUS, ESP_GER, MAR_CRO, BRA_CMR, POR_KOR] // 8C7
const teams85 = [NED_SEN, IRN_ENG, POL_ARG, FRA_AUS, ESP_GER, CRO_MAR, BRA_SRB, POR_KOR] // 8C7
const teams86 = [NED_SEN, IRN_ENG, POL_ARG, FRA_AUS, ESP_GER, CRO_MAR, BRA_CMR, POR_KOR] // 8C7
